### ISSUE TITLE
Error on building gatsby

### ISSUE THREAD

**Issue by tulikavijay** [collective/gatsby-source-plone#9] opened 2018-01-16 06:37 UTC
## Steps followed: 
```
git clone git@github.com:collective/gatsby-source-plone.git
make build
cd api
bin/instance fg
(cd tests/gatsby-starter-default && gatsby build)
```

### Actual result 
```
tux (master *) gatsby-source-plone $ (cd tests/gatsby-starter-default && gatsby build)
success delete html files from previous builds — 0.021 s
success open and validate gatsby-config.js — 0.032 s
success copy gatsby files — 0.051 s
error UNHANDLED EXCEPTION


  Error: /home/tux/workspace/gatsby-source-plone/tests/gatsby-starter-default/no  de_modules/gatsby-source-plone/gatsby-node.js:4
  exports.sourceNodes = async (
                              ^
  SyntaxError: Unexpected token (
  
  - module.js:20 require
    internal/module.js:20:19
  
  - api-runner-node.js:82 runAPI
    [gatsby-starter-default]/[gatsby]/dist/utils/api-runner-node.js:82:20
  
  - api-runner-node.js:178 
    [gatsby-starter-default]/[gatsby]/dist/utils/api-runner-node.js:178:33
  
  - map.js:27 
    [gatsby-starter-default]/[gatsby]/[async]/internal/map.js:27:9
  
  - eachOfLimit.js:64 replenish
    [gatsby-starter-default]/[gatsby]/[async]/internal/eachOfLimit.js:64:17
  
  - eachOfLimit.js:49 iterateeCallback
    [gatsby-starter-default]/[gatsby]/[async]/internal/eachOfLimit.js:49:17
  
  - onlyOnce.js:12 
    [gatsby-starter-default]/[gatsby]/[async]/internal/onlyOnce.js:12:16
  
  - map.js:29 
    [gatsby-starter-default]/[gatsby]/[async]/internal/map.js:29:13
  
  - util.js:16 tryCatcher
    [gatsby-starter-default]/[bluebird]/js/release/util.js:16:23
  
  - nodeify.js:23 Promise.successAdapter
    [gatsby-starter-default]/[bluebird]/js/release/nodeify.js:23:30
  
  - promise.js:566 Promise._settlePromise
    [gatsby-starter-default]/[bluebird]/js/release/promise.js:566:21
  
  - promise.js:606 Promise._settlePromiseCtx
    [gatsby-starter-default]/[bluebird]/js/release/promise.js:606:10
  
  - async.js:138 Async._drainQueue
    [gatsby-starter-default]/[bluebird]/js/release/async.js:138:12
  
  - async.js:143 Async._drainQueues
    [gatsby-starter-default]/[bluebird]/js/release/async.js:143:10
  
  - async.js:17 Immediate.Async.drainQueues
    [gatsby-starter-default]/[bluebird]/js/release/async.js:17:14
```
### Expected Result 
Build Successful

### Dependencies / Environment
Gatsby version: 1.1.28 
Node version : v6.9.1
Node.js version: v8.9.4
Operating System: Ubuntu 16.04

#### P.S : 
` (cd tests/gatsby-starter-default && gatsby serve)` works fine.

**Comment by tulikavijay** [comment] 2018-01-21 04:42
@tisto Am i missing something here? Any suggestions...

**Comment by tisto** [comment] 2018-01-21 20:07
@tulikavijay why don't you run "gatsby develop"? This is the command for local development. "build" and "serve" are only needed for production...

**Comment by tulikavijay** [comment] 2018-01-22 13:41
@tisto i had the same error while running `(cd tests/gatsby-starter-default && gatsby develop)` ...
same steps followed.

**Comment by tisto** [comment] 2018-01-22 20:26
@tulikavijay I really have no idea how to reproduce that error. Have you tried to run a vanilla GatsbyJS on your machine?

**Comment by tulikavijay** [comment] 2018-01-23 13:59
@tisto i have tried a few vanilla GatsbyJS projects on my machine, they work fine. 
Just to be sure i installed gatsby-source-plone again and checked the environment and all, it still results into the same error.

**Comment by tulikavijay** [comment] 2018-01-24 21:03
@tisto  I ran installation again and this is where packages for gatsby-starter-default is getting installed?
Thought i should add this too for debugging...
```
$ cross-env NODE_ENV=production npm run build

> gatsby-source-plone@0.1.0 build /home/tux/workspace/gatsby-source-plone
> babel src --out-dir . --ignore __tests__

src/gatsby-node.js -> gatsby-node.js
Done in 25.66s.
(cd tests/gatsby-starter-default && yarn install)
yarn install v1.3.2
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.1.3: The platform "linux" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "gatsby > postcss-cssnext@2.11.0" has unmet peer dependency "caniuse-db@^1.0.30000652".
warning "gatsby-plugin-react-helmet > react-helmet@5.2.0" has unmet peer dependency "react@>=15.0.0".
[4/4] Building fresh packages...
Done in 105.53s.
make[1]: Leaving directory '/home/tux/workspace/gatsby-source-plone'
make build-test
make[1]: Entering directory '/home/tux/workspace/gatsby-source-plone'
virtualenv-2.7 . || virtualenv -p /usr/bin/python .
/bin/bash: virtualenv-2.7: command not found
Running virtualenv with interpreter /usr/bin/python
New python executable in /home/tux/workspace/gatsby-source-plone/bin/python
copying /usr/bin/python => /home/tux/workspace/gatsby-source-plone/bin/python
Installing setuptools, pip, wheel...done.
bin/pip install -r requirements.txt
Collecting robotframework==3.0 (from -r requirements.txt (line 1))
Collecting robotframework-selenium2library==1.7.4 (from -r requirements.txt (line 2))
Collecting robotframework-debuglibrary==0.4 (from -r requirements.txt (line 3))
Collecting Selenium==2.53.1 (from -r requirements.txt (line 4))
  Using cached selenium-2.53.1-py2-none-any.whl
Collecting decorator>=3.3.2 (from robotframework-selenium2library==1.7.4->-r requirements.txt (line 2))
  Using cached decorator-4.2.1-py2.py3-none-any.whl
Collecting docutils>=0.8.1 (from robotframework-selenium2library==1.7.4->-r requirements.txt (line 2))
  Using cached docutils-0.14-py2-none-any.whl
Installing collected packages: robotframework, Selenium, decorator, docutils, robotframework-selenium2library, robotframework-debuglibrary
Successfully installed Selenium-2.53.1 decorator-4.2.1 docutils-0.14 robotframework-3.0 robotframework-debuglibrary-0.4 robotframework-selenium2library-1.7.4
make[1]: Leaving directory '/home/tux/workspace/gatsby-source-plone'
```
I have made the following changes to run make build on my system..
```
build-backend:
	@echo "Build"
	(cd api && virtualenv-2.7 . || virtualenv -p /usr/bin/python .)
.
.
.
build-test:
	virtualenv-2.7 . || virtualenv -p /usr/bin/python .
	bin/pip install -r requirements.txt
```

**Comment by cekk** [comment] 2018-02-03 14:00
@tulikavijay could it be a nodejs problem?

Which version are you using? 6.9.1 or 8.9.4?

**Comment by tulikavijay** [comment] 2018-02-03 14:04
I am using Nodejs - v8.9.4

**Comment by cekk** [comment] 2018-02-04 18:03
Are you sure?
Because that's an error that occurs with old node versions.
I tried with a 6.10.3 and i have exactly that error.
I don't remember from which version they introduced some es6 support (your error is relates to some es6 functionalities..arrow functions i think), but with 8.9.4 should work (i tried also with that version).

i recommend you to use [nvm](https://github.com/creationix/nvm) to manage nodejs versions and be sure which version are you using.

I'm going to make a pr with a proper .nvmrc config file

**Comment by tulikavijay** [comment] 2018-02-06 13:15
@cekk Thanks for the reply! when i checked `nodejs --version`, it would always show v8.9.4... so i was sure that couldn't be the problem. 
I checked the version using `nvm ls` and found out that wasn't the case, so i used v8.9.4 finally and its working.

**Comment by cekk** [comment] 2018-02-06 14:30
very good!
So i can close this issue

**Closed by cekk** 2018-02-06 14:30 UTC
